# Generated by Django 2.1.7 on 2019-03-21 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstprojectapp', '0003_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedules',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=128)),
                ('work', models.TextField(max_length=500)),
                ('startdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('enddate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='add',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='login',
            name='emailid',
        ),
        migrations.RemoveField(
            model_name='login',
            name='pwd',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
